=== raml-apis/Stormpath/schemas/AccountGroupsList-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "href" : {
      "type" : "string" ,
      "required" : false
    } ,
    "offset" : {
      "type" : "number" ,
      "required" : false
    } ,
    "limit" : {
      "type" : "number" ,
      "required" : false
    } ,
    "items" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "href" : {
              "type" : "string" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "description" : {
              "type" : "string" ,
              "required" : false
            } ,
            "status" : {
              "type" : "string" ,
              "required" : false
            } ,
            "directory" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "href" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "tenant" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "href" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "accounts" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "href" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "accountMemberships" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "href" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          }
        }
      ]
    }
  }
}

=== raml-apis/Stormpath/examples/GroupMembershipsList-example.json
{
  "href" : "https://api.stormpath.com/v1/accounts/MvdTIJakRO2Ry8c5z5itWw/groupMemberships" ,
  "offset" : 0 ,
  "limit" : 25 ,
  "items" : [
    {
      "href" : "https://api.stormpath.com/v1/groupMemberships/36KuRJcsfiHZjCR0Trv4yJ" ,
      "account" : {
        "href" : "https://api.stormpath.com/v1/accounts/MvdTIJakRO2Ry8c5z5itWw"
      } ,
      "group" : {
        "href" : "https://api.stormpath.com/v1/groups/tKP_30-9TcCneD3ktBwcig"
      }
    } , {
      "href" : "https://api.stormpath.com/v1/groupMemberships/1kjD3owGFAAzoGhFsO1oLz" ,
      "account" : {
        "href" : "https://api.stormpath.com/v1/accounts/MvdTIJakRO2Ry8c5z5itWw"
      } ,
      "group" : {
        "href" : "https://api.stormpath.com/v1/groups/smJGMBMpQ_-FKvMgCRTdVA"
      }
    }
  ]
}

=== raml-apis/Stormpath/examples/TenantAplications-example.json
{
  "href" : "https://api.stormpath.com/v1/tenants/cJoiwcorTTmkDDBsf02AbA/applications" ,
  "offset" : 0 ,
  "limit" : 25 ,
  "items" : [
    {
      "href" : "https://api.stormpath.com/v1/applications/WpM9nyZ2TbaEzfbRvLk9KA"
    } , {
      "href" : "https://api.stormpath.com/v1/applications/aLlyOUrBAse34js9hjiH9j"
    } , {
      "href" : "https://api.stormpath.com/v1/applications/Xhf0a9HLA02djsdP90dsQ2"
    }
  ]
}

=== raml-apis/Stormpath/examples/AccountsListresp-example.json
{
  "href" : "https://api.stormpath.com/v1/applications/cJoiwcorTTmkDDBsf02AbA/accounts" ,
  "offset" : 0 ,
  "limit" : 25 ,
  "items" : [
    {
      "href" : "https://api.stormpath.com/v1/accounts/WpM9nyZ2TbaEzfbRvLk9KA"
    } , {
      "href" : "https://api.stormpath.com/v1/accounts/aLlyOUrBAse34js9hjiH9j"
    } , {
      "href" : "https://api.stormpath.com/v1/accounts/Xhf0a9HLA02djsdP90dsQ2"
    }
  ]
}

=== raml-apis/Stormpath/examples/AccountGroupsList-example.json
{
  "href" : "https://api.stormpath.com/v1/accounts/cJoiwcorTTmkDDBsf02AbA/groups" ,
  "offset" : 0 ,
  "limit" : 25 ,
  "items" : [
    {
      "href" : "https://api.stormpath.com/v1/groups/ZgoHUG0oSoVNeU0K4GZeVQ" ,
      "name" : "Red Shirts" ,
      "description" : "" ,
      "status" : "ENABLED" ,
      "directory" : {
        "href" : "http://api.stormpath.com/v1/directories/1FaQ6kZxTL4DVJXWeXtUh7"
      } ,
      "tenant" : {
        "href" : "http://api.stormpath.com/v1/tenants/tqjB6LiESGO00qvC5dkNw"
      } ,
      "accounts" : {
        "href" : "http://api.stormpath.com/v1/groups/ZgoHUG0oSoVNeU0K4GZeVQ/accounts"
      } ,
      "accountMemberships" : {
        "href" : "http://api.stormpath.com/v1/groups/ZgoHUG0oSoVNeU0K4GZeVQ/accountMemberships"
      }
    }
  ]
}

=== raml-apis/Stormpath/examples/StoreMappingsList-example.json
{
  "href" : "https://api.stormpath.com/v1/applications/5D26Bl8lHTct1FDCHrltc3/accountStoreMappings" ,
  "offset" : 0 ,
  "limit" : 25 ,
  "items" : [
    {
      "href" : "https://api.stormpath.com/v1/accountStoreMappings/XpM9nyZ2TbaEzfbRvLk9KA"
    } , {
      "href" : "https://api.stormpath.com/v1/accountStoreMappings/aLlyOUrBAse34js9hjiH9j"
    } , {
      "href" : "https://api.stormpath.com/v1/accountStoreMappings/Xhf0a9HLA02djsdP90dsQ2"
    }
  ]
}

=== raml-apis/Stormpath/examples/DirectoriesList-example.json
{
  "href" : "https://api.stormpath.com/v1/tenants/Gh9238fksJlsieJkPkQuW/directories" ,
  "offset" : 0 ,
  "limit" : 25 ,
  "items" : [
    {
      "href" : "https://api.stormpath.com/v1/directories/bckhcGMXQDujIXpbCDRb2Q"
    } , {
      "href" : "https://api.stormpath.com/v1/directories/lIKeabOss8w9fJf0fJfb34"
    } , {
      "href" : "https://api.stormpath.com/v1/directories/Hfjks7kj9sfKfh9fhsPifa"
    }
  ]
}

=== raml-apis/Stormpath/examples/GroupsList-example.json
{
  "href" : "https://api.stormpath.com/v1/applications/cJoiwcorTTmkDDBsf02AbA/groups" ,
  "offset" : 0 ,
  "limit" : 25 ,
  "items" : [
    {
      "href" : "https://api.stormpath.com/v1/groups/WpM9nyZ2TbaEzfbRvLk9KA"
    } , {
      "href" : "https://api.stormpath.com/v1/groups/aLlyOUrBAse34js9hjiH9j"
    } , {
      "href" : "https://api.stormpath.com/v1/groups/Xhf0a9HLA02djsdP90dsQ2"
    }
  ]
}
