=== raml-apis/Stormpath/schemas/CreateAccountresp-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "href" : {
      "type" : "string" ,
      "required" : false
    } ,
    "username" : {
      "type" : "string" ,
      "required" : false
    } ,
    "email" : {
      "type" : "string" ,
      "required" : false
    } ,
    "fullName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "givenName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "middleName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "surname" : {
      "type" : "string" ,
      "required" : false
    } ,
    "status" : {
      "type" : "string" ,
      "required" : false
    } ,
    "customData" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "groups" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "groupMemberships" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "directory" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "tenant" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "emailVerificationToken" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    }
  }
}

=== raml-apis/Stormpath/examples/CreateAccountresp-example.json
{
  "href" : "https://api.stormpath.com/v1/accounts/cJoiwcorTTmkDDBsf02AbA" ,
  "username" : "jlpicard" ,
  "email" : "capt@enterprise.com" ,
  "fullName" : "Jean-Luc Picard" ,
  "givenName" : "Jean-Luc" ,
  "middleName" : "" ,
  "surname" : "Picard" ,
  "status" : "UNVERIFIED" ,
  "customData" : {
    "href" : "https://api.stormpath.com/v1/accounts/cJoiwcorTTmkDDBsf02AbA/customData"
  } ,
  "groups" : {
    "href" : "https://api.stormpath.com/v1/accounts/cJoiwcorTTmkDDBsf02AbA/groups"
  } ,
  "groupMemberships" : {
    "href" : "https://api.stormpath.com/v1/accounts/cJoiwcorTTmkDDBsf02AbA/groupMemberships"
  } ,
  "directory" : {
    "href" : "https://api.stormpath.com/v1/directories/WpM9nyZ2TbaEzfbRvLk9KA"
  } ,
  "tenant" : {
    "href" : "https://api.stormpath.com/v1/tenants/Ad8mIcavSty7XzD-xZdP3g"
  } ,
  "emailVerificationToken" : {
    "href" : "https://api.stormpath.com/v1/accounts/emailVerificationTokens/4VQxTP5I7Xio03QJTOwQy1"
  }
}
