=== raml-apis/Stormpath/schemas/CreateCloudDirectoryresp-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "href" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "status" : {
      "type" : "string" ,
      "required" : false
    } ,
    "tenant" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "accounts" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "groups" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    }
  }
}

=== raml-apis/Stormpath/examples/RetrieveDirectory-example.json
{
  "href" : "https://api.stormpath.com/v1/directories/bckhcGMXQDujIXpbCDRb2Q" ,
  "name" : "Captains" ,
  "description" : "Captains from a variety of stories" ,
  "status" : "enabled" ,
  "accounts" : {
    "href" : "https://api.stormpath.com/v1/directories/bckhcGMXQDujIXpbCDRb2Q/accounts"
  } ,
  "groups" : {
    "href" : "https://api.stormpath.com/v1/directories/bckhcGMXQDujIXpbCDRb2Q/groups"
  } ,
  "tenant" : {
    "href" : "https://api.stormpath.com/v1/tenants/Gh9238fksJlsieJkPkQuW"
  }
}

=== raml-apis/Stormpath/examples/CreateDirectoryresp-example.json
{
  "href" : "https://api.stormpath.com/v1/directories/bckhcGMXQDujIXpbCDRb2Q",
  "name" : "Captains",
  "description" : "Captains from a variety of stories",
  "status" : "enabled",
  "tenant" : {
    "href" : "https://api.stormpath.com/v1/tenants/Gh9238fksJlsieJkPkQuW"
  },
  "accounts" : {
    "href" : "https://api.stormpath.com/v1/directories/bckhcGMXQDujIXpbCDRb2Q/accounts"
  },
  "groups" : {
    "href" : "https://api.stormpath.com/v1/directories/bckhcGMXQDujIXpbCDRb2Q/groups"
  }
}
