=== raml-apis/Stormpath/schemas/RetrieveTenant-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "href" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "key" : {
      "type" : "string" ,
      "required" : false
    } ,
    "applications" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "directories" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    }
  }
}

=== raml-apis/Stormpath/examples/RetrieveTenant-example.json
{
  "href" : "https://api.stormpath.com/v1/tenants/cJoiwcorTTmkDDBsf02AbA" ,
  "name" : "My Tenant" ,
  "key" : "myTenant" ,
  "applications" : {
    "href" : "https://api.stormpath.com/v1/tenants/cJoiwcorTTmkDDBsf02AbA/applications"
  } ,
  "directories" : {
    "href" : "https://api.stormpath.com/v1/tenants/cJoiwcorTTmkDDBsf02AbA/directories"
  }
}
