=== raml-apis/Stormpath/schemas/UpdateAccountStoreMappingresp-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "href" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accountStore" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "application" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "href" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "listIndex" : {
      "type" : "number" ,
      "required" : false
    } ,
    "isDefaultAccountStore" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "isDefaultGroupStore" : {
      "type" : "boolean" ,
      "required" : false
    }
  }
}

=== raml-apis/Stormpath/examples/RetrieveAccountStoreMappings-example.json
{
  "href" : "https://api.stormpath.com/v1/accountStoreMappings/7Ui2gpn9tV75y3TExAmPLe" ,
  "accountStore" : {
    "href" : "https://api.stormpath.com/v1/directories/bckhcGMXQDujIXpExAmPLe"
  } ,
  "application" : {
    "href" : "https://api.stormpath.com/v1/applications/Uh8FzIouQ9C8EpcExAmPLe"
  } ,
  "listIndex" : 0 ,
  "isDefaultAccountStore" : true ,
  "isDefaultGroupStore" : true
}
